name: image_filter_plus
description: "A simple image filters package for making image filters easily."
version: 0.0.1
homepage: https://github.com/alvi-2081/image_filter_plus
repository: https://github.com/alvi-2081/image_filter_plus
issue_tracker: https://github.com/alvi-2081/image_filter_plus/issues

environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
